#!/usr/bin/env python3
"""Create Swedish listening notes from completed, selected radio-drama takes.

Standard library only; no credentials, network calls, rendering or listening.
Requires all selected takes and their fresh audits. Mixes are linked when present.
Only previously generated reports may be replaced; other files stay untouched.
"""

from __future__ import annotations

import argparse
from collections import Counter
import datetime as dt
import hashlib
import json
import math
import os
from pathlib import Path
import re
import sys
import tempfile
import wave


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = ROOT / "dist/stories/the-spare-room/adaptations/audio/sv/chunked-v1"
DEFAULT_INDEX = ROOT / "stories/the-spare-room/adaptations/audio/render-plans/sv-chunks/index.json"
ENGLISH_SOURCE = ROOT / "stories/the-spare-room/adaptations/audio/SCRIPT.md"
# The exact source identity recorded by the adaptation and this production.
ENGLISH_SHA256 = "ecab830f5f47c3821e2ed189d641ff6546a71c31a8c24f4e48a7af8aa6edd49e"
GENERATOR = "report_radio_chunks.py"
MARKER = f"<!-- Generated by {GENERATOR}; safe to regenerate. -->"
SPOKEN = re.compile(r"\*\*([^:*]+):\*\* (.*)")


def load(path: Path) -> dict:
    result = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(result, dict):
        raise ValueError(f"Expected a JSON object: {path}")
    return result


def sha(path: Path) -> str:
    value = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            value.update(block)
    return value.hexdigest()


def resolved(value: str | Path) -> Path:
    path = Path(value)
    return path.resolve() if path.is_absolute() else (ROOT / path).resolve()


def check_hash(path: Path, expected: str | None, description: str) -> str:
    actual = sha(path)
    if not expected or actual != expected:
        raise ValueError(f"{description}: checksum does not match: {path}")
    return actual


def escaped(text: object) -> str:
    return str(text).replace("\\", "\\\\").replace("|", "\\|").replace("[", "\\[").replace("]", "\\]").replace("\n", " ")


def link(label: str, path: Path) -> str:
    return f"[{escaped(label)}](<{path.resolve().as_posix()}>)"


def clock(seconds: float | None) -> str:
    if seconds is None:
        return "tid saknas"
    value = max(0, int(round(seconds)))
    hours, remainder = divmod(value, 3600)
    minutes, seconds = divmod(remainder, 60)
    return f"{hours}:{minutes:02}:{seconds:02}" if hours else f"{minutes}:{seconds:02}"


def finite(value) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool) and math.isfinite(value)


def wav_info(path: Path) -> dict:
    with wave.open(str(path), "rb") as handle:
        frames, rate = handle.getnframes(), handle.getframerate()
        channels, width = handle.getnchannels(), handle.getsampwidth()
        if not frames or not rate or handle.getcomptype() != "NONE":
            raise ValueError(f"Empty or unsupported WAV: {path}")
        remaining = frames
        while remaining:
            count = min(remaining, 48_000)
            if len(handle.readframes(count)) != count * channels * width:
                raise ValueError(f"Truncated WAV: {path}")
            remaining -= count
    return {"duration_seconds": frames / rate, "frames": frames,
            "sample_rate_hz": rate, "channels": channels, "sample_width_bits": width * 8}


def source_records(path: Path) -> tuple[list[dict], list[tuple[int, str]]]:
    spoken, cues = [], []
    for line in path.read_text(encoding="utf-8").splitlines():
        match = SPOKEN.fullmatch(line)
        if match:
            spoken.append({"source_index": len(spoken) + 1, "speaker": match[1], "text": match[2]})
        elif line.startswith("["):
            cues.append((len(spoken), line))
    return spoken, cues


def event_time(chunk: dict, turn: dict, detail: dict | None = None) -> dict:
    """Map an ASR location into the chosen local mix, retaining uncertainty."""
    value = (detail or {}).get("start")
    precision = "ASR word time"
    if not finite(value):
        value = turn.get("start")
        precision = "ASR turn start; missing word has no exact time"
    row = chunk["timeline"].get(turn.get("source_index"))
    if not finite(value) and row:
        value = row.get("raw_start_seconds")
        precision = "turn start from mixed source timeline"
    if not finite(value):
        return {"raw_seconds": None, "local_seconds": None, "global_seconds": None,
                "precision": "no timed words for this turn"}
    local = float(value)
    if chunk["mix"] and chunk["mix"].get("approved_mix_reused_bit_identically") and row:
        # Approved timeline already includes the original 2.2-second opening;
        # this audit's word times still refer to the original dry dialogue.
        reference = turn.get("start") if finite(turn.get("start")) else row["raw_start_seconds"]
        local += row["local_start_seconds"] - reference
    elif chunk["mix"]:
        local += chunk["mix"].get("lead_handle_seconds", 0)
        rate = chunk["audio"]["sample_rate_hz"]
        local += sum(item["frames"] / rate for item in chunk["mix"].get("silence_insertions", [])
                     if item["at_raw_frame"] <= round(value * rate))
    global_time = local + chunk["mix"]["global_start_seconds"] if chunk["mix"] else None
    return {"raw_seconds": round(value, 6), "local_seconds": round(local, 6),
            "global_seconds": round(global_time, 6) if global_time is not None else None,
            "precision": precision}


def collect(index_path: Path, output: Path, revision: str) -> dict:
    index = load(index_path)
    source = resolved(index["source"])
    source_hash = check_hash(source, index["source_sha256"], "Swedish source")
    english_hash = check_hash(ENGLISH_SOURCE, ENGLISH_SHA256, "English source")
    expected_speech, expected_cues = source_records(source)
    if len(expected_speech) != index["spoken_turns"]:
        raise ValueError("Index and source spoken counts differ.")
    selection_path = output / "selection.json"
    selection = load(selection_path) if selection_path.exists() else {}
    ids = {item["id"] for item in index["chunks"]}
    if set(selection) - ids:
        raise ValueError(f"Unknown selected chunk IDs: {sorted(set(selection) - ids)}")
    absent = []
    for spec in index["chunks"]:
        take = selection.get(spec["id"], "take-01")
        if not isinstance(take, str) or not re.fullmatch(r"take-[0-9]{2}", take):
            raise ValueError(f"Invalid take selection: {spec['id']}={take}")
        folder = output / "chunks" / spec["id"] / take
        for name in ("plan.json", "render-manifest.json", "dialogue.wav", "audit.json", "transcript.json", "transcript.meta.json"):
            if not (folder / name).is_file():
                absent.append(str(folder / name))
    if absent:
        raise ValueError("All selected chunks must finish rendering and auditing first. Missing:\n" + "\n".join(absent))
    chunks, actual_speech, actual_cues = [], [], []
    cast = None
    after = 0
    for spec in index["chunks"]:
        take = selection.get(spec["id"], "take-01")
        folder = output / "chunks" / spec["id"] / take
        plan_path = folder / "plan.json"
        plan, manifest, audit = load(plan_path), load(folder / "render-manifest.json"), load(folder / "audit.json")
        frozen_hash = sha(resolved(spec["plan"]))
        check_hash(plan_path, frozen_hash, "Selected plan versus frozen plan")
        check_hash(plan_path, manifest.get("plan_sha256"), "Rendered plan")
        audio_hash = check_hash(folder / "dialogue.wav", manifest.get("wav_sha256"), "Rendered WAV")
        if plan.get("source_sha256_at_preparation") != source_hash:
            raise ValueError(f"Prepared source identity differs: {spec['id']}")
        if plan.get("model_id") != "eleven_v3" or plan.get("language_code") != "sv":
            raise ValueError(f"Unexpected model or language: {spec['id']}")
        for name, path in (("audio", folder / "dialogue.wav"), ("plan", plan_path), ("transcript", folder / "transcript.json")):
            check_hash(path, audit.get("inputs", {}).get(name, {}).get("sha256"), f"Audit input {name}")
        provenance = load(folder / "transcript.meta.json")
        if (provenance.get("status") != "success" or provenance.get("input_sha256") != audio_hash
                or audit.get("transcript_provenance", {}).get("audio_checksum_matches") is not True):
            raise ValueError(f"Transcript provenance does not match selected WAV: {spec['id']}")
        if (audit.get("source_coverage", {}).get("exact_match") is not True
                or audit["source_coverage"].get("source_sha256") != source_hash):
            raise ValueError(f"Source audit is stale or failed: {spec['id']}")
        voices = {role: value["voice_id"] for role, value in plan["voices"].items()}
        if cast is None:
            cast = plan["voices"]
        elif voices != {role: value["voice_id"] for role, value in cast.items()}:
            raise ValueError(f"Cast differs across selected chunks: {spec['id']}")
        source_turns = [item for item in plan["items"] if item.get("source_spoken") is True]
        wanted_indices = list(range(spec["start"], spec["end"] + 1))
        if [item.get("source_index") for item in source_turns] != wanted_indices:
            raise ValueError(f"Wrong source range: {spec['id']}")
        for item in plan["items"]:
            if item.get("source_spoken") is True:
                after = item["source_index"]
                actual_speech.append({key: item[key] for key in ("source_index", "speaker", "text")})
            elif item.get("kind") == "comment":
                actual_cues.append((after, item["comment"]))
        render_items = [item for item in plan["items"] if item.get("kind") != "comment"]
        if [(item["speaker"], item["text"]) for item in render_items] != [(item["speaker"], item["text"]) for item in audit["turns"]]:
            raise ValueError(f"Audit turn ordering differs: {spec['id']}")
        api_chars = sum(len(" ".join(part for part in (item.get("tags", "").strip(), item.get("text", "").strip()) if part)) for item in render_items)
        if api_chars != spec["characters"] or api_chars > 2000:
            raise ValueError(f"API character count differs or exceeds limit: {spec['id']}")
        mix_path = folder / f"{revision}-manifest.json"
        mix = load(mix_path) if mix_path.exists() else None
        path = folder / "dialogue.wav"
        if mix:
            if mix.get("take") != take or mix.get("chunk_id") != spec["id"]:
                raise ValueError(f"Mix identity differs: {mix_path}")
            for name, input_path in (("plan", plan_path), ("dialogue", folder / "dialogue.wav")):
                check_hash(input_path, mix.get("input_hashes", {}).get(name), f"Mix input {name}")
            if not spec.get("reused"):
                check_hash(folder / "audit.json", mix.get("input_hashes", {}).get("asr_timing"), "Mix ASR timing")
            if mix.get("all_source_pcm_preserved_before_gain") is not True:
                raise ValueError(f"Source PCM preservation not verified: {mix_path}")
            path = resolved(mix["path"])
            check_hash(path, mix.get("wav_sha256"), "Mixed WAV")
            if spec.get("reused"):
                origin = load(folder / "approved-origin.json")
                check_hash(path, origin.get("mix_sha256"), "Approved opening mix reuse")
        audio = wav_info(path)
        if mix and (mix["frames"] != audio["frames"] or abs(mix["duration_seconds"] - audio["duration_seconds"]) > 1 / audio["sample_rate_hz"]):
            raise ValueError(f"Mix duration differs from WAV: {path}")
        timeline = {row["source_index"]: row for row in mix.get("source_timeline", [])} if mix else {}
        chunks.append({**spec, "take": take, "folder": folder, "plan": plan,
                       "manifest": manifest, "audit": audit, "mix": mix, "path": path,
                       "audio": audio, "timeline": timeline, "first": source_turns[0],
                       "last": source_turns[-1], "wav_sha256": sha(path)})
    if actual_speech != expected_speech:
        raise ValueError("Selected chunks do not preserve every source turn exactly once and in order.")
    if actual_cues != expected_cues:
        raise ValueError("Selected chunks do not preserve every source cue once at its original position.")
    full_path = output / "mixes" / revision / "manifest.json"
    full = load(full_path) if full_path.exists() else None
    if full:
        expected = [(chunk["id"], chunk["take"], chunk["wav_sha256"]) for chunk in chunks]
        got = [(item["chunk_id"], item["take"], item["wav_sha256"]) for item in full["chunks"]]
        if expected != got:
            raise ValueError("Full mix uses a different take selection or different chunk audio.")
        for item in full["files"]:
            check_hash(resolved(item["path"]), item.get("sha256"), "Full/act export")
        if abs(sum(chunk["audio"]["duration_seconds"] for chunk in chunks) - full["duration_seconds"]) > .001:
            raise ValueError("Full mix duration differs from its selected chunks.")
    return {"index_path": index_path, "index": index, "output": output, "revision": revision,
            "source": source, "source_hash": source_hash, "english_hash": english_hash,
            "chunks": chunks, "cast": cast, "source_turns": len(expected_speech),
            "source_cues": len(expected_cues), "full": full, "full_manifest_path": full_path,
            "selection_path": selection_path}


def candidates(bundle: dict) -> tuple[list[dict], list[dict], dict]:
    lexical, voice_events = [], []
    stats = Counter()
    for chunk in bundle["chunks"]:
        for turn in chunk["audit"]["turns"]:
            if not turn.get("source_spoken"):
                stats["planned_reaction_turns"] += 1
                continue
            stats["source_turns"] += 1
            if turn.get("all_expected_tokens_matched"):
                stats["all_expected_words_matched_turns"] += 1
            if turn.get("asr_fidelity_review_needed"):
                stats["lexical_review_turns"] += 1
            for field in ("missing", "substitutions", "insertions"):
                for detail in turn.get(field, []):
                    stats[field] += 1
                    lexical.append({"chunk_id": chunk["id"], "take": chunk["take"],
                                    "source_index": turn["source_index"], "speaker": turn["speaker"],
                                    "source_text": turn["text"], "kind": field,
                                    "expected": detail.get("expected"), "observed": detail.get("observed"),
                                    **event_time(chunk, turn, detail)})
            if turn.get("differs_from_role_majority"):
                voice_events.append({"chunk_id": chunk["id"], "source_index": turn["source_index"],
                                     "speaker": turn["speaker"], "speaker_id": turn.get("majority_speaker_id"),
                                     "short_evidence": bool(turn.get("speaker_evidence_uncertain")),
                                     "source_text": turn["text"], **event_time(chunk, turn)})
    return lexical, voice_events, dict(stats)


def audio_links(bundle: dict) -> list[str]:
    if not bundle["full"]:
        return ["Helmix och aktfiler finns ännu inte för denna mixversion.", ""]
    files = {Path(item["path"]).name: resolved(item["path"]) for item in bundle["full"]["files"]}
    links = [link(label, files[name]) for name, label in (("gastrummet-sv.wav", "Hela pjäsen · WAV"), ("gastrummet-sv.mp3", "Hela pjäsen · MP3"), ("chunks.m3u", "Spellista")) if name in files]
    acts = [link(f"A{i}", files[f"a{i}-sv.mp3"]) for i in range(1, 8) if f"a{i}-sv.mp3" in files]
    return [" · ".join(links), "", "Akter: " + " · ".join(acts), ""]


def render_readme(bundle: dict, stats: dict) -> str:
    mixed = all(chunk["mix"] for chunk in bundle["chunks"])
    duration = sum(chunk["audio"]["duration_seconds"] for chunk in bundle["chunks"])
    final_check = bundle["output"] / "FINAL_CHECK.md"
    lines = [MARKER, "", "# Gästrummet – svensk radioteater", "",
             f"{len(bundle['chunks'])} lyssningsdelar, sammanlagt {clock(duration)}. "
             + ("Länkarna nedan spelar mixen med röster och ljud." if mixed else "Delar utan färdig mix länkar till den omixade dialogen."), "",
             *audio_links(bundle),
             link("Samlat ljudmanus med regi och rösttaggar", bundle["output"] / "render-script.md") + " · "
             + link("Svenskt källmanus", bundle["source"]) + " · " + link("Detaljerad kvalitetskontroll", bundle["output"] / "QA.md")
             + (" · " + link("Teknisk slutkontroll av mixen", final_check) if final_check.is_file() else ""), "",
             "Det godkända öppningsprovet är återanvänt. Övriga delar kan bytas var för sig utan att hela pjäsen behöver renderas om.", "",
             "Ge gärna återkoppling som **003 + 0:30** följt av det du hör. Tiden avser den länkade delens början; använd gärna hela del-ID:t vid omtagningar.", "",
             "Roller: " + "; ".join(f"{role.title()}: {voice['name']}" for role, voice in bundle["cast"].items()) + ". Kim har pronomen hen.", "",
             "## Lyssningsdelar", "", "| Del · vald tagning | Längd | Källturer | Börjar → slutar |", "| --- | ---: | ---: | --- |"]
    for chunk in bundle["chunks"]:
        first, last = escaped(chunk["first"]["text"]), escaped(chunk["last"]["text"])
        label = f"{chunk['id']} · {chunk['take']}"
        if not chunk["mix"]:
            label += " · omixad"
        lines.append(f"| {link(label, chunk['path'])} | {clock(chunk['audio']['duration_seconds'])} | {chunk['start']}–{chunk['end']} | ”{first}” → ”{last}” |")
    lines.extend(["", "## Vad som har kontrollerats", "",
                  f"Alla {bundle['source_turns']} källturer är ordagrant bevarade i underlaget, i rätt ordning. Alla {bundle['source_cues']} scenanvisningar finns som kommentarer som inte läses upp. Källornas och de valda filernas kontrollsummor har verifierats.", "",
                  f"Automatisk återtranskribering matchar samtliga väntade ord i {stats.get('all_expected_words_matched_turns', 0)}/{bundle['source_turns']} källturer efter dokumenterad stavningsnormalisering. {stats.get('lexical_review_turns', 0)} turer har saknade, ersatta eller extra ord i transkriberingen och listas i QA-rapporten. Det är lyssningskandidater, inte fastställda fel i framförandet.", "",
                  "Rapporten intygar inte subjektiv avlyssning av hela pjäsen. Uttal, skådespeleri, rytm, röstskillnader och ljudbalans behöver bedömas genom lyssning.", ""])
    return "\n".join(lines)


def render_script(bundle: dict) -> tuple[str, dict]:
    """One readable performance script, preserving selected item order exactly."""
    headings = {}
    for line in bundle["source"].read_text(encoding="utf-8").splitlines():
        match = re.fullmatch(r"## (A[1-7])\s+—\s+(.+)", line)
        if match:
            headings[match[1]] = line
    counts = Counter()
    lines = [MARKER, "", "# Gästrummet – fullständigt ljudmanus", "",
             "Källrepliker och berättartext återges ordagrant från det svenska manuset, i den ordning de skickades till de valda tagningarna. Rollnamn, delmarkeringar och instruktioner läses inte upp.", "",
             "**RUT**, **HELENA** och **KIM** är skådespelarroller. **BERÄTTARE** är den separata berättarrösten. "
             "Block märkta **Regi — läses inte upp** är manusets scen- och ljudanvisningar, visade här för läsning. "
             "**Rösttagg** visar instruktionen till ElevenLabs. **Tillagd reaktion** markerar separat tillförda skratt eller andetag; dessa är inte källrepliker.", "",
             "Roller: " + "; ".join(f"{role.title()}: {voice['name']}" for role, voice in bundle["cast"].items()) + ". Kim har pronomen hen.", "",
             "Ljuddelarnas ID och tagningar följer " + link("lyssningsöversikten", bundle["output"] / "README.md")
             + ". Delmarkeringarna är läshjälp och innebär inga hörbara aktpresentationer.", ""]
    section = None
    for chunk in bundle["chunks"]:
        pending_locator = True
        counts["chunks"] += 1
        for item in chunk["plan"]["items"]:
            item_section = item.get("section", chunk["section"])
            if item_section != section:
                if item_section not in headings:
                    raise ValueError(f"Missing source section heading: {item_section}")
                lines.extend([headings[item_section], ""])
                section = item_section
            if item.get("kind") == "comment":
                # Leading comments may belong to the previous act. Keep them
                # before the new act heading and its first spoken turn.
                lines.extend([f"> **Regi — läses inte upp:** {item['comment']}", ""])
                counts["unspoken_source_cues"] += 1
                continue
            if pending_locator:
                label = f"Ljuddel {chunk['id']} · {chunk['take']}"
                lines.extend([link(label, chunk["path"]) + f" · källturer {chunk['start']}–{chunk['end']}", ""])
                pending_locator = False
            if item.get("tags"):
                lines.extend([f"*Rösttagg:* `{item['tags']}`", ""])
            if item.get("source_spoken") is True:
                lines.extend([f"**{item['speaker']}:** {item['text']}", ""])
                counts["source_turns"] += 1
                if item.get("kind") == "narration":
                    counts["narration_turns"] += 1
            elif item.get("kind") == "reaction":
                lines.extend([f"**Tillagd reaktion – {item['speaker']}:** {item['text']}", ""])
                counts["added_reaction_turns"] += 1
            else:
                raise ValueError(f"Unknown performance item: {chunk['id']} {item.get('kind')}")
    if (counts["source_turns"] != bundle["source_turns"]
            or counts["unspoken_source_cues"] != bundle["source_cues"]):
        raise ValueError("Combined performance script changed the verified source coverage.")
    return "\n".join(lines), dict(counts)


def render_qa(bundle: dict, lexical: list[dict], voice_events: list[dict], stats: dict) -> str:
    by_id = {chunk["id"]: chunk for chunk in bundle["chunks"]}
    final_check = bundle["output"] / "FINAL_CHECK.md"
    lines = [MARKER, "", "# Gästrummet – automatiskt kvalitetsprotokoll", "",
             "Detta protokoll skiljer kontrollerat indataunderlag från osäker automatisk avlyssning. Saknade eller ersatta ASR-ord kan bero på taligenkänningen. Ingen mänsklig slutlyssning av hela pjäsen intygas här.", "",
             *([link("Separat teknisk slutkontroll: ljudmått, sammanfogning och H3/H4", final_check), ""] if final_check.is_file() else []),
             "## Identitet och fullständighet", "",
             f"- Svenskt manus: {link('SCRIPT.md', bundle['source'])}; SHA-256 `{bundle['source_hash']}`.",
             f"- Engelskt original: {link('SCRIPT.md', ENGLISH_SOURCE)}; SHA-256 `{bundle['english_hash']}`; oförändrat mot den fastställda originalversionen.",
             f"- Fryst index: {link('index.json', bundle['index_path'])}; SHA-256 `{sha(bundle['index_path'])}`.",
             f"- {bundle['source_turns']}/{bundle['source_turns']} källturer och {bundle['source_cues']}/{bundle['source_cues']} scenanvisningar återfinns exakt en gång, i rätt ordning och med rätt talare respektive position.",
             "- Valda tagningars plan-, ljud- och transkriptfiler matchar sina manifest och auditunderlag. Samma fyra röst-ID används i alla delar.",
             "- Modell: ElevenLabs eleven_v3 Text to Dialogue; svenska. Första godkända tagningen återanvänds. Extra skratt och andetag är separat märkta reaktioner, inte nya källrepliker.", "",
             "## Valda filer och nivåindikatorer", "",
             "Nivåvärdena nedan gäller omixad dialog. Fullskaliga PCM-sampel är en indikator att kontrollera; de bevisar inte hörbar distorsion. Mixens limiter återställer inte eventuell distorsion i originaltagningen.", "",
             "| Del | Tagning | Länkad ljudfil | Dialoglängd | Fullskaliga sampel i dialog | SHA-256 för länkad WAV |", "| --- | --- | --- | ---: | ---: | --- |"]
    for chunk in bundle["chunks"]:
        audio = chunk["audit"]["audio"]
        lines.append(f"| {chunk['id']} | {chunk['take']} | {link('Mix' if chunk['mix'] else 'Dialog', chunk['path'])} | {clock(audio['duration_seconds'])} | {audio.get('full_scale_sample_count', 'okänt')} | `{chunk['wav_sha256']}` |")
    if bundle["full"]:
        first = bundle["chunks"][0]
        if not first["mix"].get("approved_mix_reused_bit_identically"):
            raise ValueError("The full mix does not report bit-identical approved opening reuse.")
        lines.extend(["", f"Helmix: {clock(bundle['full']['duration_seconds'])}. {link('Mixmanifest', bundle['full_manifest_path'])}.",
                      "Mixmanifesten dokumenterar att ingen källdialog har klippts eller tidssträckts. Pauser läggs till vid behov; det godkända öppningsprovet kopieras bitidentiskt. Detta är teknisk kontroll, inte bevis för att alla pauser eller ljudnivåer fungerar konstnärligt.",
                      "Ingen musik eller musikalisk rumston har lagts till. Tillagda pauspartier är digital tystnad; ingen separat rumstonsinspelning har skapats. Befintligt rumsljud i tagningarna finns kvar."])
    lines.extend(["", "## Textåtergivning enligt ASR", "",
                  f"Alla väntade ord återfinns efter normalisering i {stats.get('all_expected_words_matched_turns', 0)}/{bundle['source_turns']} källturer. {stats.get('lexical_review_turns', 0)} turer behöver textkontroll genom lyssning: {stats.get('missing', 0)} saknade ord, {stats.get('substitutions', 0)} ersättningar och {stats.get('insertions', 0)} infogade ord i ASR-resultatet.", "",
                  "Jämförelsen bortser från skiljetecken och versaler. Vanliga stavnings- och mellanrumsvarianter normaliseras; exempelvis sen/sedan kan ändå ha olika betydelse i ett enskilt sammanhang. Därför är full normaliserad träff inte samma sak som bevisad ordagrann ljudåtergivning. Namn, synonymer och siffror rättas inte automatiskt.", "",
                  "Tiderna är ungefärliga och kommer från ordtidsatt taligenkänning, inte de driftande API-tidsstämplarna. De lokala tiderna avser länken för aktuell del. För ett saknat ord utan egen tid används replikens början, när den är känd. Replikens tidsgränser bygger på matchade eller ersatta ord; infogade ljud eller ord får inte ensamma förlänga den. Infogade ord mellan repliker kan ha hänförts till föregående replik och kan även vara skratt eller andra vokaliseringar.", ""])
    normalizations = {}
    for chunk in bundle["chunks"]:
        normalization = chunk["audit"].get("normalization", {})
        normalizations.update(normalization.get("swedish_word_variants", {}))
        normalizations.update(normalization.get("swedish_spacing_variants", {}))
    if normalizations:
        lines.extend(["Tillämpade normaliseringar: " + "; ".join(f"{escaped(a)} → {escaped(b)}" for a, b in sorted(normalizations.items())) + ".", ""])
    if lexical:
        lines.extend(["| Del + lokal tid | Källtur · roll | ASR-avvikelse att lyssna på | Källreplik |", "| --- | --- | --- | --- |"])
        for item in lexical:
            chunk = by_id[item["chunk_id"]]
            label = f"{item['chunk_id']} + ≈{clock(item['local_seconds'])}"
            time_note = f" (rå dialog ≈{clock(item['raw_seconds'])})"
            if item["kind"] == "missing":
                change = f"Saknas i ASR: ”{escaped(item['expected'])}”. Tid = replikstart."
            elif item["kind"] == "substitutions":
                change = f"Väntat ”{escaped(item['expected'])}”, ASR ”{escaped(item['observed'])}”."
            else:
                change = f"Extra i ASR: ”{escaped(item['observed'])}”."
            lines.append(f"| {link(label, chunk['path'])}{time_note} | {item['source_index']} · {item['speaker']} | {change} | {escaped(item['source_text'])} |")
    else:
        lines.extend(["Inga saknade, ersatta eller infogade ord har markerats för källrepliker efter normalisering."])
    lines.extend(["", "## Röstkluster – osäker maskinell kontroll", "",
                  "Speaker-ID:n är tillfälliga kluster inom en del, inte verifierade rollidentiteter. Fasta röstbyten kan undgå analysen och korta repliker kan hamna fel. Samma röst-ID i beställningen bevisar inte att modellen behöll rätt röst i varje ljudtur.", "",
                  "| Del | Möjliga sammanslagningar | Instabila rollkluster |", "| --- | --- | --- |"])
    for chunk in bundle["chunks"]:
        voices = chunk["audit"]["voice_qa"]
        merges = ["/".join(item["roles"]) + (" (kort/osäkert underlag)" if item.get("uncertain") else "") for item in voices.get("possible_role_merges", [])]
        unstable = [f"{role} ({info.get('majority_fraction', 0):.0%} i huvudklustret)" for role, info in voices.get("roles", {}).items() if info.get("possible_instability")]
        lines.append(f"| {chunk['id']} | {escaped('; '.join(merges) or 'Inga flaggor')} | {escaped('; '.join(unstable) or 'Inga flaggor')} |")
    if voice_events:
        lines.extend(["", "Repliker som avviker från rollens dominerande kluster inom samma del:", "",
                      "| Del + lokal tid | Källtur · roll | Underlag | Replik |", "| --- | --- | --- | --- |"])
        for item in voice_events:
            chunk = by_id[item["chunk_id"]]
            label = f"{item['chunk_id']} + ≈{clock(item['local_seconds'])}"
            evidence = "Kort replik; särskilt osäkert" if item["short_evidence"] else "Kontrollera genom lyssning"
            lines.append(f"| {link(label, chunk['path'])} | {item['source_index']} · {item['speaker']} | {evidence} | {escaped(item['source_text'])} |")
    lines.extend(["", "## Råa underlag", "",
                  link("Samlat ljudmanus: samtliga valda delar med regi, taggar och markerade reaktioner", bundle["output"] / "render-script.md"), ""])
    for chunk in bundle["chunks"]:
        lines.append(f"- {chunk['id']} {chunk['take']}: " + " · ".join(link(label, chunk["folder"] / name) for label, name in (("Ljudmanus", "render-script.md"), ("ASR-audit", "audit.json"), ("Renderingsmanifest", "render-manifest.json"))))
    lines.extend(["", "Ljudets uttryck, uttal, kontinuitet mellan tagningar och dramaturgiska effekt återstår alltid att bedöma med öronen. Ingen godkänd skådespelar- eller publikgranskning av hela inspelningen påstås.", ""])
    return "\n".join(lines)


def write_reports(output: Path, files: dict[str, str]) -> None:
    output.mkdir(parents=True, exist_ok=True)
    for name in files:
        path = output / name
        if path.exists():
            if path.is_symlink():
                raise ValueError(f"Refusing to replace a symlink: {path}")
            if name.endswith(".json"):
                safe = load(path).get("generated_by") == GENERATOR
            else:
                safe = path.read_text(encoding="utf-8").startswith(MARKER)
            if not safe:
                raise ValueError(f"Existing report was not generated by this program; preserve or rename it first: {path}")
    for name, content in files.items():
        temporary = None
        try:
            with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=output, prefix=f".{name}.", suffix=".tmp", delete=False) as handle:
                temporary = Path(handle.name)
                handle.write(content)
            os.replace(temporary, output / name)
        finally:
            if temporary is not None:
                temporary.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--index", type=Path, default=DEFAULT_INDEX)
    parser.add_argument("--revision", default="mix-v1")
    args = parser.parse_args()
    if not re.fullmatch(r"mix-[a-z0-9][a-z0-9-]*", args.revision):
        parser.error("Use a mix revision such as mix-v1.")
    bundle = collect(args.index.resolve(), args.output.resolve(), args.revision)
    lexical, voice_events, stats = candidates(bundle)
    script, script_counts = render_script(bundle)
    if script_counts.get("added_reaction_turns", 0) != stats.get("planned_reaction_turns", 0):
        raise ValueError("Combined script and selected audits have different reaction counts.")
    summary = {
        "generated_by": GENERATOR, "generated_at_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
        "source": {"path": str(bundle["source"]), "sha256": bundle["source_hash"],
                   "exact_input_source_turns": bundle["source_turns"], "exact_source_cues": bundle["source_cues"],
                   "english_original_sha256": bundle["english_hash"]},
        "revision": args.revision, "cast": bundle["cast"], "asr_statistics": stats,
        "lexical_listening_candidates": lexical, "voice_listening_candidates": voice_events,
        "subjective_listening_performed_by_this_program": False,
        "combined_render_script": {"path": str(bundle["output"] / "render-script.md"), **script_counts},
        "chunks": [{"id": chunk["id"], "take": chunk["take"], "path": str(chunk["path"]),
                    "wav_sha256": chunk["wav_sha256"], "mixed": chunk["mix"] is not None,
                    "source_start": chunk["start"], "source_end": chunk["end"],
                    "duration_seconds": chunk["audio"]["duration_seconds"],
                    "first_text": chunk["first"]["text"], "last_text": chunk["last"]["text"]}
                   for chunk in bundle["chunks"]],
    }
    files = {"README.md": render_readme(bundle, stats), "QA.md": render_qa(bundle, lexical, voice_events, stats),
             "render-script.md": script,
             "qa-summary.json": json.dumps(summary, ensure_ascii=False, indent=2) + "\n"}
    write_reports(bundle["output"], files)
    print(json.dumps({"reports": [str(bundle["output"] / name) for name in files],
                      "chunks": len(bundle["chunks"]), "source_turns": bundle["source_turns"],
                      "source_cues": bundle["source_cues"], "asr_statistics": stats,
                      "combined_render_script": script_counts,
                      "lexical_listening_candidates": len(lexical), "voice_listening_candidates": len(voice_events)},
                     ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, KeyError, TypeError, wave.Error) as error:
        print(f"Report failed: {error}", file=sys.stderr)
        raise SystemExit(1)
